### ISSUE TITLE
Footer Partial not rendering at the bottom of the screen.

### ISSUE THREAD

**Issue by thisisrajneel** [thisisrajneel/EJS-Blog-Site#1]
The home layout is made using Header and Footer partial. When the home page has a lot of articles, the footer is stuck at the original position and the articles are rendered behind the footer.

**Comment by ddepu11** [comment]
Put position: relative in body tag rule.
![Screenshot 2021-08-10 140548](https://user-images.githubusercontent.com/16676672/128835930-dd5165e3-03e7-4690-bbd4-4fc9b2ff5d34.png)

**Comment by thisisrajneel** [comment]
Thanks a lot!
